package edu.illinois.finalproject.ZomatoAPIFiles;

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Created by alexandregeubelle on 10/30/17.
 */

public class RestaurantL3 implements Parcelable {
    private int id;
    private String name;
    private String url;
    private ResLocation location;
    private int average_cost_for_two;
    private int price_range;
    private String currency;
    private String thumb;
    private String featured_image;
    private String photos_url;
    private String menu_url;
    private String events_url;
    private UserRating user_rating;
    private int has_online_delivery;
    private int is_delivering_now;
    private int has_table_booking;
    private String deeplink;
    private String cuisines;
    /*
     * The following variables are "partner access" only:
    private int all_reviews_count;
    private int photo_count;
    private String phone_numbers;
    private Photo[] photos;
    private Review[] all_reviews;
    */

    public RestaurantL3() {

    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getUrl() {
        return url;
    }

    public ResLocation getLocation() {
        return location;
    }

    public int getAverage_cost_for_two() {
        return average_cost_for_two;
    }

    public int getPrice_range() {
        return price_range;
    }

    public String getCurrency() {
        return currency;
    }

    public String getThumb() {
        return thumb;
    }

    public String getFeatured_image() {
        return featured_image;
    }

    public String getPhotos_url() {
        return photos_url;
    }

    public String getMenu_url() {
        return menu_url;
    }

    public String getEvents_url() {
        return events_url;
    }

    public UserRating getUser_rating() {
        return user_rating;
    }

    /**
     * The variable must be stored as an int because of how its value is passed in Json,
     * here we correct this by returning a boolean.
     * @return returns the variable as a boolean, even though it is stored as an integer.
     */
    public boolean Has_online_delivery() {
        return has_online_delivery == 1;
    }

    /**
     * The variable must be stored as an int because of how its value is passed in Json,
     * here we correct this by returning a boolean.
     * @return returns the variable as a boolean, even though it is stored as an integer.
     */
    public boolean Is_delivering_now() {
        return is_delivering_now == 1;
    }

    /**
     * The variable must be stored as an int because of how its value is passed in Json,
     * here we correct this by returning a boolean.
     * @return returns the variable as a boolean, even though it is stored as an integer.
     */
    public boolean Has_table_booking() {
        return has_table_booking == 1;
    }

    public String getDeeplink() {
        return deeplink;
    }

    public String getCuisines() {
        return cuisines;
    }

    // Autogenerated by Android studio plugin to allow for passing of object through intent.
    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeInt(this.id);
        dest.writeString(this.name);
        dest.writeString(this.url);
        dest.writeParcelable(this.location, flags);
        dest.writeInt(this.average_cost_for_two);
        dest.writeInt(this.price_range);
        dest.writeString(this.currency);
        dest.writeString(this.thumb);
        dest.writeString(this.featured_image);
        dest.writeString(this.photos_url);
        dest.writeString(this.menu_url);
        dest.writeString(this.events_url);
        dest.writeParcelable(this.user_rating, flags);
        dest.writeInt(this.has_online_delivery);
        dest.writeInt(this.is_delivering_now);
        dest.writeInt(this.has_table_booking);
        dest.writeString(this.deeplink);
        dest.writeString(this.cuisines);
    }

    protected RestaurantL3(Parcel in) {
        this.id = in.readInt();
        this.name = in.readString();
        this.url = in.readString();
        this.location = in.readParcelable(ResLocation.class.getClassLoader());
        this.average_cost_for_two = in.readInt();
        this.price_range = in.readInt();
        this.currency = in.readString();
        this.thumb = in.readString();
        this.featured_image = in.readString();
        this.photos_url = in.readString();
        this.menu_url = in.readString();
        this.events_url = in.readString();
        this.user_rating = in.readParcelable(UserRating.class.getClassLoader());
        this.has_online_delivery = in.readInt();
        this.is_delivering_now = in.readInt();
        this.has_table_booking = in.readInt();
        this.deeplink = in.readString();
        this.cuisines = in.readString();
    }

    public static final Creator<RestaurantL3> CREATOR = new Creator<RestaurantL3>() {
        @Override
        public RestaurantL3 createFromParcel(Parcel source) {
            return new RestaurantL3(source);
        }

        @Override
        public RestaurantL3[] newArray(int size) {
            return new RestaurantL3[size];
        }
    };
}
